### ISSUE TITLE
Hide/Show Capability

### ISSUE THREAD

**Issue by simarmata535** [spheras/desktopfolder#100]
Please add Hide and Show feature that could execute from Desktop's Hotcorner, and use it with animation seems to be a very nice capability, yes, I refer to MacOS's Dashboard but not really the same.

**Comment by spheras** [comment]
Do you mean to show / hide the desktop? like the Super-D hotkey?

**Comment by simarmata535** [comment]
No, I don't. I mean the app (the whole Desktop Folder) acts like widgets on MacOS Dashboard, only shown when the mouse cursor go to the specific corner of the monitor, but what needed on the app is just a command to show and hide all.

CMIIW, Super+D hotkey only hide regulars windows but not the DesktopFolder's elements.

**Comment by spheras** [comment]
So, what you mention is to bring to front all the panels when the mouse cursor goes to a specific corner, isnt it?  (sorry, i'm not a macos user, I don't know how it works)

**Comment by simarmata535** [comment]
nevermind the MacOS Dashboard then :-)

so the feature i meant is a command parameter to hide all panels and to show them back in always on top state.

the execution will be handle by gala's Hot Corner on elementaryos or another apps alike on anyother distro.

as an addition to that, probably animation and dark background will be very nice.

**Comment by aljelly** [comment]
From my understanding, what is being requested is: When you trigger the hide function, all the panels are made invisible, so you can only see your desktop wallpaper. When you set them to show again, they become visible again.

Ideally they would fade in and out (probably easy with CSS animations/transitions and opacity).

I was also thinking that this feature would be nice. Fences (the Windows equivalent) has a feature like this, except instead of a hot corner, you double click an empty area of the desktop to show/hide panels. Fences also allows you to exclude individual panels and icons from hiding when you hide everything else.

On my Windows installation with Fences everything on the desktop is nearly always hidden, except one icon (the Recycle Bin). I pretty much never use the desktop apart from that.

**Comment by simarmata535** [comment]
that will also do it, @aljelly - to make it maybe more clear or bring some ideas, desktop-folder can act like dock, but since the area is the whole desktop, the trigger will be more versatile than dock's more like slingshot's.

**Comment by eljefuri** [comment]
I like this idea, but the problem is that it is better for things like the note widget than it is for desktop icons. Right @simarmata535 ?

**Comment by spheras** [comment]
this feature was included for the next version 1.1.0 thanks to @aljelly
