### ISSUE TITLE
"Super+D" doesn't always work

### ISSUE THREAD

**Issue by uncertainquark** [spheras/desktopfolder#106]
Even after adding Desktop Folder to 'Startup applications', the app doesn't always autostart and thus "Super+D" doesn't work multiple times. The panels themselves work just fine however. 

Sorry the bug report isn't too specific, please let me know what would you need to debug this and I shall provide the required.

**Comment by spheras** [comment]
Hi @uncertainquark, thanks for reporting. You don't need to add it manually to any folder to autostart the application. The application should start thanks to the .desktop file located here at `/etc/xdg/autostart`.
There is a file called com.github.spheras.desktopfolder.desktop, if you open it you'll see these settings:

`X-GNOME-Autostart-enabled=true`
`X-GNOME-Autostart-phase=Running`

That's enough to autostart the application, at least in elementary. What OS are you running? Are you using X or wayland? What changes when it is not autostarted?

Regarding the Super+D, it sounds strange. First because this is a shortcut installed in the SO (the first time you run desktopfolder). You can see this shortcut if you open the system settings panel->keyboard->shortcuts.  Under the custom section you will see something like:

`/usr/bin/com.github.spheras.desktopfolder show-desktop`

I mean, it is not necessary to have the application opened to use this functionality. The only problem is that you will not see the application, you will see your empty desktop if desktopfolder is not launched before.

**Comment by uncertainquark** [comment]
Hi, I'm running elementary OS itself, 0.4.1 Loki. I do have a panel running yet "Super+D" doesn't always work.

**Comment by fossfreedom** [comment]
Can I clarify why we are discussing Super+D?  This is a shortcut key to hide/show running applications on GNOME based desktop-environments

**Comment by spheras** [comment]
In elementary OS we don't have a Super+D shortcut key by default. The application install it, pointing to itself to allow that beahvior.  Anyway, the application code regarding this is very short, just calling the Wnck library:

```
unowned Wnck.Screen screen = Wnck.Screen.get_default ();
screen.toggle_showing_desktop (show);
```

The only sensible part is the `show` flag. It is calculated determining if there are normal windows not minimized.

**Comment by spheras** [comment]
I'm closing the issue. (only apply to elementary os)  In principle, the shortcut is installed and it calls to Wnck to do its magic. We need to confirm that it is installed correctly, execute it manually, check the shortcut installation and so. Please, reopen in case you have more hints about the issue.
