### ISSUE TITLE
Automatically arrange icons when panel is resized [link panel]

### ISSUE THREAD

**Issue by eljefuri** [spheras/desktopfolder#140]
When creating a link panel (and possibly other panels), icons apparently do not get rearranged and there seems to be no way to do this. So for example if I add a new item to a folder, that icon simply sits above others by default. Likewise, if I resize the panel window it should automatically re-arrange the icons.

**Comment by spheras** [comment]
Hi @eljefuri. Yes, you can't. Currently, we don't have a real arrangement system.  We introduced in the last version the auto arrangement for new panels, but is very basic yet. We have the alignment option for a panel, but is not the same obviously.

A first approximation could be adding a setting to allow auto arrangement and forbid the mouse icon drag.  A problem might appear when the icons don't all fit in the panel, because panels don't have any scrolls system, but.. ignoring, this the first part could be relatively easy to implement. How do you see that?

**Comment by spheras** [comment]
I will close this issue to describe the new feature into #148.
