### ISSUE TITLE
Highlight over photos

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#151]
On budgie desktop when you mouse over a photo there is a highlight around the photo. That highlight takes approx 2 to 3 seconds to disappear when you move the mouse away.

This jars poorly compared to the .5 second highlight fade of an icon or folder.

Thoughts why this is happening and where in the  code base to investigate further?

**Comment by spheras** [comment]
Yes, that was a change I did in the last release (I mean, it is happening also in elementary).  The idea behind the highlight is to show to the user where are the borders of the photo window because are needed to resize it. 

Anyway, I agree with you that maybe it is too much time. I will check it with .5 seconds.

**Comment by spheras** [comment]
Take a look at the changes, I think it is better now.
