### ISSUE TITLE
Don't show an icon on the dock.

### ISSUE THREAD

**Issue by donadigo** [spheras/desktopfolder#18]
Permamently showing an icon in the dock isn't really useful, specialy when you can't perform any action from the right-click menu on the dock.

**Comment by spheras** [comment]
Hello @donadigo, thankyou for reporting.

Regarding the icon at the dock (plank) panel, **I agree with you**. The only situation when the icon appears (confirm in your case too please) is when you click the application launcher from Slingshot panel.  DesktopFolder install an autostart launcher into the system, and when it is launched automatically after relogin/restart the icon isn't shown.

Perhaps this is enough for you, or in general... anyway I agree that it shouldn't be shown in any case.  I don't know exactly why the icon is shown because all the windows have the `skip-taskbar-hint=true`. So, in theory, as far as I know, the shouldn't be shown at the status bar.

I've been investigating and, I'm not 100% sure but it seems a "Plank issue"... You can read more here:
[How Can I Open an Application Without Showing It In Dock](https://elementaryos.stackexchange.com/questions/3354/how-can-i-open-an-application-without-showing-it-in-dock) 

I've been reading the Plank code for a while, and it seems that it doesn't take into account this hint from Windows... but I need to investigate more.  I will keep you informed if I discover something new.

**Comment by aljelly** [comment]
Since 1.0.2 the icon seems to disappear after hanging around for about 10 seconds if you launch it from Applications, even if you do `killall com.github.spheras.desktopfolder` and then launch Desktop Folder again from Applications.

**Comment by spheras** [comment]
Yes, that's probably the only we can do by now. When I tryed some days ago desktopfolder over last Ubuntu 17.10, the icon was always there :(, even if it was started automatically after login... I don't know why, but maybe is also wayland (starting to hate it :laughing: ).

**Comment by spheras** [comment]
adding the comments from @aljelly to the postinst. Closing this issue.
