### ISSUE TITLE
Remove "About" dialog and corresponding context menu item

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#23]
[Here's an article](https://medium.com/elementaryos/peace-out-about-dialogs-8efa956c0562) from the elementary OS team giving the reason for this.

I would also recommend removing the "Press ⌘-D to show Desktop" context menu item, this is already in the AppCenter description, and it doesn't look so nice in the context menu.

(I have a branch that makes these changes)

**Comment by spheras** [comment]
I've read the article and I still have doubts.  The most important doubt is that this application can still run in Gnome3 as well, and I think it is important to maintain the compability. I'm saying that probably there can exist users that aren't on elementary (i.e. the last ubuntu version with gnome) and they don't have the AppCenter.  One solution for this could be to show the menu only for other distros. I'm not sure how I can do this.

Other doubt is about the need to show the number version of the application currently running (not the available at the AppCenter), and the license, which could include (not now) the mention to other projects/artists... and son on.  This could be a legal requirement. Not sure if AppCenter can support all this information (i've only seen a link to the license)

Regarding the "Press ⌘-D to show Desktop", I agree with you that it is ugly, but i'm afraid that users doesn't know it. For me it is very important to use the shortcut, because, if not, the app is not very usable: You must go fast to the desktop to see your notes/folders etc...  But yes, this info is on the AppCenter (if you are on elementary)

So... I don't know if we should delete them, maintain only for other distros, or just be brave and remove that. To be honest, the popup is now beautiful :smile:

**Comment by aljelly** [comment]
I see... the GNOME 3 users who download the deb won't see the information that would be visible in the AppCenter for an elementary OS user.

Plank (elementary's dock) has a slightly hidden settings page where you have to right click the dock while holding Ctrl to see the Settings menu item. Also, I think eventually right clicking or dragging anywhere on the desktop should be added (will create an issue for this eventually).

So with those in mind, perhaps something like that could be done: when Ctrl is held and you right click on the desktop (i.e. not on a panel or photo or note), an Info/Settings page could show as a menu item. That could have a panel with 3 tabs: options, key shortcuts and the about page. I'll create a new issue for this.

I'll add the About page back meanwhile, though there won't be a way to see it.
