### ISSUE TITLE
Scale photos relative to aspect ratio

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#24]
When the photo is created, it should be scaled relative to it's aspect ratio. Otherwise it just looks like this:

![2017-10-20 12_58_21-elementary os running - oracle vm virtualbox](https://user-images.githubusercontent.com/10395308/31819849-7db238e4-b596-11e7-944e-517757180982.png)

When resizing, preserve the aspect ratio of the photo either by default or by holding a modifier key (which is Ctrl in Inkscape).

**Comment by spheras** [comment]
Yes, I agree. I'm not sure how to do that, because the photo is adjusting to the invisible window... So, I'm not sure if I can restrict the dimension of the window while you are resizing it, or... perhaps, maintain the photo aspect, and when you release the boton, resize the window to the final real photo dimensions.

**Comment by spheras** [comment]
![peek 28-10-2017 02-24](https://user-images.githubusercontent.com/3862933/32129409-284eba02-bb87-11e7-8b41-07abb0d2beee.gif)
done! Hope it is ok.
(by the way , the picture is from the genius David Revoy)
