### ISSUE TITLE
release 1.1.0

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#255]
I think it is time to release! we have now a lot of new functionality since the last version published (maybe too much :D) and I start feeling that we need to concentrate on the stabilization of that new functionality adding patches to that release.

This issue is also to thank everyone (contributors like @aljelly, @jica, @fossfreedom, @Jacob-Vlijm,  you are the best!! thank you everyone!!) and give you the opportunity to stop/pause the release, to fix/add something relevant, or just comment whatever.

If nothing happens, I hope during the Thursday/Friday or weekend, I will release the .deb and try to publish it to the elementary appcenter.

**Comment by fossfreedom** [comment]
Indeed ... way overdue - but simply superb!

Congrats @spheras on a brilliant release.  Your dogged determination has been instrumental to this.

Look forward to continue working with you. 

FYI - the next Debian upload opportunity will now be from May/June onwards since Debian is now in freeze state.  This affects Ubuntu as well since just targeted fixes are now trickling through.

As you say - Elementary will get this immediately.  People can install directly through your .deb - and UB will continue the daily PPA to test new stuff as it becomes available.

**Comment by Chronigan** [comment]
Just a heads up, I just updated through the aur and in the properties window it still says version 1.0.10. Don't know if that is a problem there or a typo.

**Comment by spheras** [comment]
The release was committed time ago, but the approval for elementary OS is still being processed (I don't know why, usually they were very fast). I'm closing this issue meanwhile.

**Comment by spheras** [comment]
finally approved at the Elementary App Center
