### ISSUE TITLE
[BUG] Size of panel change when I connect my second monitor

### ISSUE THREAD

**Issue by gquittet** [spheras/desktopfolder#256]
### Description

The size of the panel change when I use my second monitor.

### Steps to reproduce
1. Connect a monitor with a different resolution.
2. See the panel size are now different than before.

### Expected result
The size of the desktop folder haven't to be change. 

### System Information
- OS: elementary OS 5.0
- Desktop Folder version: 1.0.10

**Comment by gquittet** [comment]
I change the resolution strategy to "Scale" inside the settings and I'll see what will happens.

**Comment by spheras** [comment]
Hi @gquittet, thanks for reporting. Depending on the strategy you use the behavior will be different. By default the STORE strategy will preserve the same size you configured in different resolutions. Anyway, I'm trying to publish the new 1.1.0 version in the Elementary AppCenter. This version is a major release with tons of bugs fixed and new features. I'm waiting the aproval. I say this because maybe you should check this in the new version. (or you can download from releases section directly)

**Comment by gquittet** [comment]
@spheras Great job! :+1:

**Comment by gquittet** [comment]
This update has fixed my problem 😀 Thank you ! 👍
