### ISSUE TITLE
Support for viewing hidden files

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#42]
Would include a "Show Hidden Files" option in the dropdown menu, just like Files. This is probably most useful for link panels (#32).

This feature would probably require a blacklist for `.desktopfolder`, `*.dfn` and `*.dfp` files.

**Comment by spheras** [comment]
I don't see the need to show hidden files in a panel. I mean, when I need that, is because i'm doing some terminal issue, or at least with a file explorer like Files.. but in panels? Have you found an use case where this is useful? 
Anyway, you know that I'm not closed to have configured items in an setting window, I'm open to that.  If you really think this is necessary, we can implement this easily.

**Comment by aljelly** [comment]
Closing for the time being. Indeed, I'm not sure if there's a useful case for it. Maybe if someone makes an issue or comments here and presents a useful case for it, we could reopen it.
