### ISSUE TITLE
Super D shortcuts hides panels and docks

### ISSUE THREAD

**Issue by danrabbit** [spheras/desktopfolder#5]
This makes the desktop unusable

**Comment by spheras** [comment]
Thanks @danrabbit for reporting. I've tried it on several Loki installations and it seems to work like a charm. Maybe the problem is that you had a previous Super-D shortcut with a call to the Windows Manager (Gala if Im not wrong) Show Desktop, you know, sending a _NET_SHOWING_DESKTOP.. Is that possible? It seems to happen something similar in Gnome3 (ubuntu gnome flavour).

Desktopfolder try to install a shortcut to "improve" the toggle_showing_desktop from wnck, because the problem is that this function minimize everything but DOCK/DESKTOP type windows.  For instance, Nimbus app is minimized as well when the "Show Desktop" button on plank is pressed.

I decided to type all the desktopfolder windows to DOCK windows, but the problem seems that DOCK windows can't move or resize (or get text focus).. So I did an ugly trick to put NORMAL/DOCK type on each window depending on the situation.. Now it seems to work very well using my own Show Desktop or Wnck toggle_showing_desktop.

Any ideas on how to create resizable, moveable, editable DOCK windows? This is my first GTK app, I'm a novice.

I will try to publish again with this modification.

Thanks again (and I wouldn't want to miss the opportunity to say thanks for the great job you are doing with elementary. A fan here)
