### ISSUE TITLE
Can't change desktop wallpaper image

### ISSUE THREAD

**Issue by mugbug** [spheras/desktopfolder#60]
**Steps to reproduce:**
1. Go to System Settings -> Desktop -> Wallpaper
2. Select some wallpaper different from the current one
3. Press ⌘-D to show desktop (or simply minimize all windows)

**Expected result:**
The desktop wallpaper changes to the chosen one.

**Obtained result:**
The desktop wallpaper image does not change.

_Note:_ The wallpaper changes on the loggin page.

**Comment by aljelly** [comment]
I just tried what you described, I can't reproduce the issue. It's changing fine for me. 

If it's Desktop Folder that is causing this, then that would be strange, because I'm pretty sure Desktop Folder doesn't actually do anything to the wallpaper. Can you please try the following?

- Restart your computer, log in and try changing the wallpaper again
- Open the terminal and type `killall com.github.spheras.desktopfolder` and try changing the wallpaper again
- Run `env G_MESSAGES_DEBUG=all com.github.spheras.desktopfolder`, try changing the wallpaper again and see if anything appears in the terminal when you do this.
- Uninstall Desktop Folder from AppCenter (you won't lose anything) and restart your computer again. Try changing the wallpaper again.

If it's not working at this point, it may be an issue with elementary or some other app you have installed. In this case, try the following:
- Open the terminal, type `date` in it, but don't run it yet. Position the terminal window in a way where you can quickly click the window and press enter.
- Go to System Settings -> Desktop -> Wallpaper
- Change the wallpaper, then quickly switch to the terminal window and press enter. You now have the approximate time (to the second) you tried to change the wallpaper.
- Open a new terminal tab and run `less /var/log/syslog`. Press the END button to go to the bottom of the log.
- See if there's anything 1 second before, on or just after the time that shows in the other terminal tab where you ran `date`.

Hopefully that will help you find what's causing the problem. You'll probably want to post your issue on the [elementary OS StackExchange](https://elementaryos.stackexchange.com/).

(When doing that I get `gnome-session[2067]: (gala:2290): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`, but the wallpaper still changes as expected, so those messages probably aren't related to your problem.)

**Comment by mugbug** [comment]
Ok, I now fixed the issue by **killing the Desktop Folder process** and **restarting my computer**. 

I tried to reproduce the issue again by uninstalling the Desktop Folder, restarting my computer and installing it again, but this time the issue didn't happen. Therefore, I couldn't figure out what caused the problem.

Anyway, it works fine now, thanks for your support and for this awesome app!
