### ISSUE TITLE
Serbian translation

### ISSUE THREAD

**Issue by pavlepiramida** [spheras/desktopfolder#61]
Im almost done with Serbian translations for this beautiful utility,and I was wondering how to submit the .po 

Should I make a pull or something else?(Ive never did translations before)

**Comment by spheras** [comment]
Hi @pavlepiramida! thank you very much for the translation, it is more than welcome :smile:. The easiest way is doing a pull request, but if you prefer, you can attach it to this issue and I  will add to the master branch. 

Text is something that is easily modified from one version to the next, so, depending on the snapshot you get from the code, you will need to update some translations just before the final release. Currently we are working on the 1.0.3 version, which maybe could be delivered on two weeks (but is just a personal estimation, nothing is closed yet).

Again, thank you very much for the collaboration.

**Comment by aljelly** [comment]
If you want to make a pull request for your translation, here's how:

First create a fork of this repository on GitHub. Then `git clone` your version of the repository (which would be `https://github.com/pavlepiramida/desktopfolder`). See [GitHub's fork a repo page](https://help.github.com/articles/fork-a-repo/#platform-linux) for information on forking and cloning a repo.

Put your Serbian translation file (`sr.po`) in the `po/` folder, then `git add po/sr.po`. Then `git commit -m "Add Serbian translation"`. Then `git push` your changes to your fork's repo.

Once you've done that, you can create a pull request on GitHub for your fork and we can review and merge it.

As @spheras said, we're currently working on version 1.0.3. You might want to delay submitting a pull request until we make a release candidate for 1.0.3, because until then there's probably going to be changes/additions/removals to text. When the RC is ready we could @mention you in a "Translations for 1.0.3-rc" issue or something if you want.

In the meantime you can keep your forked repo in sync with the main repo by setting this one as upstream (see the forking and cloning link above) and then fetching and merging every so often (see [this GitHub page on syncing a fork](https://help.github.com/articles/syncing-a-fork/#platform-linux)).

**Comment by pavlepiramida** [comment]
Thank you so much for very comprehensive explanation,I am familiar with git enough to make pulls and what not :D 

Well I currently build and use your master branch and thats the one I translated.
I will checkout 1.0.3 to see if theres any difference in strings and I will be more careful next time when choosing branch to translate!

By the end of the day Ill have both translations  for Serbian (cyrilic and latin,since both letters are in use).

Once more,thank you for comprehensive and pretty fast response !!

**Comment by aljelly** [comment]
The master branch is what will become 1.0.3, a 1.0.3 branch doesn't actually exist yet. Stay on master for the time being.

It's just master is highly subject to change as we add, remove and fix things.

**Comment by pavlepiramida** [comment]
I hope you dont mindme writing up here,but seems theres an issue :/
![2017-11-02 20-53-56](https://user-images.githubusercontent.com/18991480/32347252-52f92d72-c010-11e7-815d-219b98fe45eb.png)

Ive set locals to Serbian,and yet Panel is still in English.
This is on elementaryOS (in gnome-boxes,I use Arch) and with fresh master branch compiled.
Did I label translation wrong or is it elementary issue?

**Comment by aljelly** [comment]
How are you running Desktop Folder? I believe you have to run `sudo ninja install && com.github.spheras.desktopfolder` (and not `./com.github.spheras.desktopfolder` which is the executable in the build folder) in order to see translations.

Once My First Panel has been created, the name of it won't change because it's then a directory (`~/Desktop/My First Panel/`). Did you set the language to Serbian first before running, or did you run Desktop Folder before changing the language?

Is this the only place where the translation didn't appear? Can you see your translations in other places?

From quickly looking at the source files both the string and your translation seem to be formatted correctly, however it could require more investigation.

**Comment by pavlepiramida** [comment]
As you recommended in README.md after compile I did install with sudo ninja,and started it from term.
**I DID** ran desktopfolder before changing the language.
Just to make sure I rebooted,cleared MyFirstPanel folder,restarted com.github.spheras.desktopfolder but the issue is the same 

Right-clicking on Note header
![2017-11-02 21 30 19](https://user-images.githubusercontent.com/18991480/32348905-a950b046-c015-11e7-8dab-57c44832ef44.png)

Right-clicking on the body 
![2017-11-02 21 30 30](https://user-images.githubusercontent.com/18991480/32348921-b7a91f0c-c015-11e7-8eb8-97d5465b498b.png)

**Comment by spheras** [comment]
@pavlepiramida, I don't have too much experience with po translations, but you only need two things to translate the app:

1. the list of available languages in linguas file: https://github.com/pavlepiramida/desktopfolder/blob/master/po/LINGUAS
2. all the .po files listed there

When I install the app withe `sudo ninja install`, the result is:

```
.....
Installing /home/spheras/projects/desktopfolder/build/po/es.gmo to /usr/local/share/locale/es/LC_MESSAGES/com.github.spheras.desktopfolder.mo
Installing /home/spheras/projects/desktopfolder/build/po/lt.gmo to /usr/local/share/locale/lt/LC_MESSAGES/com.github.spheras.desktopfolder.mo
Installing /home/spheras/projects/desktopfolder/build/po/fr.gmo to /usr/local/share/locale/fr/LC_MESSAGES/com.github.spheras.desktopfolder.mo
Installing /home/spheras/projects/desktopfolder/build/po/fr_FR.gmo to /usr/local/share/locale/fr_FR/LC_MESSAGES/com.github.spheras.desktopfolder.mo
Installing /home/spheras/projects/desktopfolder/build/po/sr_RS.gmo to /usr/local/share/locale/sr_RS/LC_MESSAGES/com.github.spheras.desktopfolder.mo
Installing /home/spheras/projects/desktopfolder/build/po/sr_RS@latin.gmo to /usr/local/share/locale/sr_RS@latin/LC_MESSAGES/com.github.spheras.desktopfolder.mo
```

So, the translations are all installed (confirm this in your case). The last point is to ensure that your locale is one of the available ones, if not, the default is English. I say that because I don't know exactly what specific locale is sr_RS or sr_RS@latin... I mean, in the case of spanish, I have a generic one `es` to cover all other spanish (center/south america mainly) (but in fact my translation is `es_ES` - spanish from spain) ...

If everything is OK, maybe you need to create the .deb installation, I don't know :(

**Comment by pavlepiramida** [comment]
Ill figure it out,its probably something minor that I've overlooked :/
Tomorrow Ill have some spare time so Ill try to get to the bottom of this!
