### ISSUE TITLE
Prevent widgets going off-screen

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#64]
issue #63 demonstrate that in some cases widgets can be out of screen, i.e., when your monitor has a higher resolution, and after it changes and some widgets are outside the screen.

We need to check if the widget is outside the screen to move it inside again.

**Comment by aljelly** [comment]
I was going to post an issue for this, here it is:

## Handle resolution changes

Currently, if you change the display resolution to one that is smaller, any desktop objects that are placed in a position that exceed the new resolution will be off screen, whether partially or fully. If an object is fully off screen it's basically lost unless you change the resolution back to at least the size it was previously.

This would be a problem if someone were to switch their monitor with one with a smaller resolution (maybe they're switching from 4K to 1080p or something). If they had any small desktop objects positioned in the bottom right corner, they might not be able to get them back, even though they're still there.

What should happen if the user changes the resolution? I think the best way would be to scale the objects to the new resolution.

As a reference, Fences does this by letting the user choose in the settings what happens when the resolution is changed. There's 3 settings: one does nothing and the second scales objects up and down. The third option also scales but stores desktop objects positions and sizes for each resolution. So for example, there are different position and size settings for 1920 x 1080 and 1270 x 720. I think in pretty much all cases we want to do either 2 or 3.

So here's (at least) two ways it could work for Desktop Folder:
### The slightly more complicated way
- User has always had 1920 x 1080 as the resolution since they started using Desktop Folder.
- They change to 1270 x 720. Each object's size and position is scaled down to the new resolution (we might want to align these objects to a grid if we have that feature in the future). However, each object's settings for 1920 x 1080 are kept.
- They decide then to change the resolution back to 1920 x 1080. Instead of scaling the objects up from the lower resolution, the object's sizes and positions for 1920 x 1080 are restored.
- If an object has since been moved, the 1920 x 1080 setting for it is invalidated and it's upscaled.
### Or, the simple way
We could just upscale or downscale size and positions every time. The only problem is that it could introduce position/size inaccuracies.

If we eventually have a position/resizing object grid, we could use it to reduce any inaccuracies in upscaling (by snapping the object dimensions and position to this grid once upscaled).

**Comment by spheras** [comment]
Great description. What I intented to do was the simplest way: if the bounding box of a widget is outside the screen, then move inside.  But, after reading your comments, I've realized that the store of positions for each resolution could be very useful.  I will try that.

**Comment by spheras** [comment]
Wow, it was a good fight against json-glib and vala :rofl: 
It seems to be working now, but I would like if you @aljelly could make some tests because there are a lot of different cases... 

Now you have 3 options to configure at the key com.github.spheras.desktopfolder.resolution-strategy
0 -> NONE, just like now, all the widgets remains in their positions
1-> SCALE, widgets adjust their position and size to the new resolution
2-> STORE, widgets use the last position saved for the resolution and can restore it for the same screen resolution (if the widget don't have information about the new resolution, it uses scale instead)

Waiting your confirmation to close the issue.

**Comment by aljelly** [comment]
The main functionality of scaling when the resolution changes is working. Desktop windows seem to be scaling correctly. I tested panels, notes and photos and measured the numbers (at least for size). However there are a few issues:

- If you change the resolution, resize or move a desktop window and then change the resolution back to the previous one, the desktop window reverts to it's previous size or position.
  - We should discard a desktop window's previous resolution settings and scale it again if it's been moved or resized since. I haven't looked at the code closely so I don't know if this has been tried or not.
  
- If you position a desktop window just below wingpanel and then change the resolution, sometimes it gets moved underneath wingpanel. Haven't looked to see what is causing this.

- It looks like the text-shadow and text-bold options aren't being loaded correctly anymore. They seem to be writing correctly however so I'm assuming it was unintentional.

I've only tried the default option so far (which is Store).

Minor note, but maybe we should do [what Files does](https://github.com/elementary/files/blob/master/data/schemas/io.elementary.files.gschema.xml) in the gschema file and assign names to enum values (see [here](https://github.com/elementary/files/blob/master/src/Application.vala#L249) and then [here](https://github.com/elementary/files/blob/master/src/View/IconView.vala#L85) for how the enum is used). It's not necessary though.

**Comment by spheras** [comment]
I did some changes to fix 2 and 3.
Regarding 1, now store configuration dont scale if the resolution is not found. Some improvements were added also.

**Comment by spheras** [comment]
I close this issue. Reopen if necessary.

**Comment by aljelly** [comment]
@spheras I thought of a possible solution on this a week or two ago but I'm not sure about it. I was trying to think of a simple solution that was effective and didn't have any problems. I haven't thought about it since though. I'll put it here for you to consider:

## Solution

(In reply to your comments)

What I was describing was when you change the resolution on the same screen. I found it weird that when you change the resolution on the same screen, it switched to a previous layout. But I also tried connecting my laptop to the screen and I can see the usefulness of storing a different layout for multiple monitors.

I thought about it for a bit and did a little investigating. I think I may have a solution.

Some notes:
- The resolution of more than one screen is seen as a larger resolution
- We can't really uniquely identify a monitor. (but we don't need to anyway).
- I don't know if we can tell the resolution of individual monitors.

First, we store the amount of monitors somewhere, and for each monitor, it's manufacturer and model. We either store this in a file or in the gsettings. We could also store the resolution with this as well. So in a JSON format it might look like:
```json
"resolution-w": "3840",
"resolution-h": "1080",
"monitor-count": 2,
"monitors": [
  {
    "manufacturer": "The Monitor Company",
    "model": "MNTR-24A-QX"
  },
  {
    "manufacturer": "The Monitor Company",
    "model": "MNTR-24A-QX"
  }
]
```

With this we know if the monitors have changed while Desktop Folder is not running, for example if the monitors were changed when the computer was off.

We store the manufacturer and model because then we will know if the max resolution of a monitor has *potentially* changed. If the amount of plugged in monitors and the manufacturers/models for each one are the same then we can assume the user likely just changed the resolution via settings.

So when the resolution changes:
- If the amount of monitors have changed, we use the stored resolution (if there is none, scale)
- However if you have the same amount of monitors, check if each monitor is the same manufacturer and model as what you had previously plugged in.
  - If we have a monitor that wasn't known previously, we use the stored configuration
    - If there is no configuration then either do nothing or scale (or ask the user).
    *(quick afterthought: maybe in this case change the behaviour depending on if there's a new amount of monitors or not? e.g. scale if there are no new monitors, and do nothing when a monitor is added or removed)*
  - If there are the same amount of monitors and each monitor manufacturer and model matches the stored one, then scale (because we are assuming the user just changed the resolution).

Here's a very rough estimation of what that would look like:
```vala
// ... when the resolution changes
bool monitors_have_changed = compare_monitor_info_with_new ();
if (monitors_have_changed) {
    use_stored_resolution_layout ();
    // if there's no resolution found, either don't do anything, or scale.
    // (quick afterthought: maybe change the behaviour depending on if there's a new amount of monitors or not? e.g. scale if there are no new monitors, and do nothing when a monitor is added or removed)
} else {
    scale ();
}


private bool compare_monitor_info_with_new () {
    Gdk.Display display = Gdk.Display.get_default ();
    int new_monitor_count = display.get_n_monitors ();
    if (new_monitor_count != stored_monitor_count) {
        return true;
    } else {
        for (int i = 0; i < new_monitor_count; i++) {
            Gdk.Monitor monitor = display.get_monitor (i);
            if (monitor.get_manufacturer () != stored_monitor_manufacturer || monitor.get_model () != stored_monitor_model) {
                return true;
            }
        }
        return false;
    }
}
```
