### ISSUE TITLE
Panels and Photos show up in the Multitasking View

### ISSUE THREAD

**Issue by Philip-Scott** [spheras/desktopfolder#7]
As the title says, panels and photos show up on top of the multitasking view, but not Notes 

I'm gusseting you need to play a bit more with the window types ;) 
![screenshot from 2017-10-17 12 36 07](https://user-images.githubusercontent.com/10786508/31679760-c6b3c154-b337-11e7-9cf4-9dedcaecc7aa.png)

**Comment by spheras** [comment]
ups! yes, you are right @Philip-Scott , I didn't check that when I changed the window types! :smile: 
I'll submit a patch moving all the window types to DESKTOP, because it seems the best option. With DOCK type, the panel is also flickering when moving to another workspace.

Thanks for reporting @Philip-Scott !!

**Comment by spheras** [comment]
patch commited
