### ISSUE TITLE
Alert when deleting elements from panels

### ISSUE THREAD

**Issue by jica** [spheras/desktopfolder#74]
When you press Supr over any panel elements it is deleted without asking anything.

**Comment by aljelly** [comment]
Do you mean the Delete button? Do you mean items in a panel, or the desktop window itself?

At the moment, **almost everything is sent to Trash**. I don't think you can actually permanently delete an item or desktop window at the moment, even with Shift held down (it shows the alert for panel items but still doesn't permanently delete).

The only thing that *is* permanently deleted without warning are Photos, but this is only because we are deleting the .dfp file, not the image. The reasoning behind deleting the .dfp file was that it's easy to add the photo back and redo size/position/colors, and it's less confusing than finding some .dfp file in your Trash. The actual image is untouched (this is why it is worded "Remove" as in "Remove from Desktop" rather than "Delete").

I'm not sure what you were specifically referring to, so I wrote out both options:

## Delete button over desktop windows

We're removing desktop windows without an alert because they're sent to the Trash. The idea is, if it's non destructive, we don't show an alert. It can easily be found and restored from the Trash.

However, it _would_ likely be confusing if a user **accidentally pressed Delete on a panel or note and it disappears without warning**, like if a user tries to delete an item in a panel when nothing's selected. This is probably easy to do.

Two solutions to this:
1. Remove the keyboard shortcut for trashing desktop windows
2. Require a modifier to be held down at the same time, like Ctrl

## Delete button over panel items (files and folders)

Like with desktop windows, files and folders are removed without an alert because they always go to the Trash. But it's much harder to do this accidentally (you have to actually select the item first, and then press delete).

This is also consistent with the behavior of Files. If you press Delete on an item, it sends the item to the Trash. It only shows an alert if you try to permanently delete an item (Shift + Delete).

I think this way makes sense. We **should show an alert before permanent deletion**, but not when sending to Trash.
